" Use Vim settings, rather than Vi settings (much better!).
" This must be fist, because it changes other options as a side effect.
set nocompatible

" Disable viminfo.
let skip_defaults_vim=1
set viminfo=""

" Keep 100 lines of command line history.
set history=100

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Use the OS clipboard by default (on versions compiled with `+clipboard`).
set clipboard=unnamed

" Display imcomplete commands.
set showcmd

" Enables a menu at the bottom of the vim/gvim window.
set wildmenu

" Always shot the statusline.
set laststatus=2

" Show the cursor position all the time.
set ruler

" Show linenumbers.
set number

" Switch syntax highlighting on.
syntax on

" Enable filetype plugins.
:filetype plugin on

" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start
