#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Fix QuicklookStephen (Notarizing macOS Software Before Distribution)
xattr -cr $HOME/Library/QuickLook/QLStephen.qlgenerator
qlmanage -r
qlmanage -r cache
killall Finder
